---

version: '3'

services:

  client:
    build: ./client
    container_name: client
    working_dir: /var/www/html
    command: make start
    ports:
      - "4200:4200"
    restart: always
    links:
      - server

  server:
    build: ./server
    container_name: server
    working_dir: /var/www/html
    command: make start
    ports:
      - "8000:8000"
    restart: always
    links:
      - db

  db:
    image: mysql:5.7.27
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
    ports:
      - "3306:3306"
    restart: always